from __future__ import annotations

# Machine-readable implementation map. "credential_gate" means the code path exists and fails
# visibly until the external provider credentials are configured. "model_gate" applies only to
# the optional deep Open-CD enhancement; the real multispectral baseline remains operational.
FEATURE_CAPABILITIES = [
{"id":1,"name":"Real Satellite Monitoring","status":"WORKING","endpoints":["/api/satellite/latest","/api/map/satellite-layer"],"sources":["Copernicus Data Space","Element 84 Earth Search"]},
{"id":2,"name":"Forest Cover Monitoring","status":"WORKING_WITH_OPTIONAL_EE","endpoints":["/api/layers","/api/earth-engine/layer/dynamic_world_trees"],"sources":["Dynamic World","GFW"]},
{"id":3,"name":"AI Deforestation Detection","status":"WORKING_BASELINE_DEEP_MODEL_OPTIONAL","endpoints":["/api/analysis/remote-change","/api/ai/change-model/status"],"sources":["Sentinel-2 L2A"]},
{"id":4,"name":"Before–After Satellite Comparison","status":"WORKING","endpoints":["/api/map/compare","/api/analysis/remote-change"]},
{"id":5,"name":"Multi-Spectral Analysis","status":"WORKING","endpoints":["/api/map/satellite-layer","/api/analysis/remote-change"],"indices":["NDVI","NDMI","NBR","NDWI"]},
{"id":6,"name":"Multi-Layer Earth Map","status":"WORKING","endpoints":["/api/layers","/api/map/gfw-layer","/api/earth-engine/layer/{layer_id}","/api/bhuvan/tile/{z}/{x}/{y}.png"]},
{"id":7,"name":"Deep Region Investigation","status":"WORKING","endpoints":["/api/investigate","/api/analysis/evidence-chain"]},
{"id":8,"name":"Temperature Intelligence","status":"WORKING","endpoints":["/api/weather","/api/climate/anomaly"]},
{"id":9,"name":"Weather Intelligence","status":"WORKING","endpoints":["/api/weather"]},
{"id":10,"name":"Drought & Water Stress","status":"WORKING","endpoints":["/api/climate/anomaly","/api/weather","/api/earth-engine/layer/jrc_water_occurrence"]},
{"id":11,"name":"Fire & Heat Detection","status":"CREDENTIAL_GATED","endpoints":["/api/fire","/api/earth-engine/layer/modis_burned_area"],"credential_gate":"FIRMS_MAP_KEY for NRT fire points; Earth Engine auth for MODIS raster"},
{"id":12,"name":"Vegetation Health","status":"WORKING","endpoints":["/api/analysis/vegetation-series","/api/map/satellite-layer?mode=ndvi"]},
{"id":13,"name":"Environmental Anomaly Radar","status":"WORKING","endpoints":["/api/intelligence/anomaly-radar","/api/climate/anomaly"]},
{"id":14,"name":"AI Forest Doctor","status":"WORKING","endpoints":["/api/intelligence/forest-doctor","/api/analysis/evidence-chain"]},
{"id":15,"name":"Smart Warning System","status":"WORKING","endpoints":["/api/intelligence/risk","/api/analysis/evidence-chain"]},
{"id":16,"name":"Threat Prediction","status":"WORKING_BASELINE","endpoints":["/api/intelligence/predict","/api/intelligence/predict-location"],"note":"Transparent trend baseline with uncertainty; not certainty."},
{"id":17,"name":"Threat Cascade Engine","status":"WORKING","endpoints":["/api/intelligence/cascade"]},
{"id":18,"name":"AI Priority Engine","status":"WORKING","endpoints":["/api/intelligence/risk","/api/intelligence/compare-regions"]},
{"id":19,"name":"Investigation/Patrol Optimizer","status":"WORKING","endpoints":["/api/patrol","/api/patrol/road-route"],"sources":["OSRM","OpenStreetMap"]},
{"id":20,"name":"AI What-If Simulator","status":"WORKING","endpoints":["/api/intelligence/what-if"]},
{"id":21,"name":"Intervention Engine","status":"WORKING","endpoints":["/api/intelligence/intervention"]},
{"id":22,"name":"Recovery Intelligence","status":"WORKING","endpoints":["/api/intelligence/recovery","/api/analysis/recovery-location"]},
{"id":23,"name":"Recovery Exit Conditions","status":"WORKING","endpoints":["/api/intelligence/recovery","/api/analysis/recovery-location"]},
{"id":24,"name":"Forest Resilience Score","status":"WORKING","endpoints":["/api/intelligence/resilience"]},
{"id":25,"name":"Protected Area Intelligence","status":"WORKING_WITH_AUTH_OPTIONS","endpoints":["/api/protected-areas","/api/earth-engine/value/wdpa_protected"],"credential_gate":"Protected Planet token or Earth Engine authentication"},
{"id":26,"name":"Forest Fragmentation Analysis","status":"WORKING","endpoints":["/api/analysis/fragmentation","/api/analysis/remote-change"]},
{"id":27,"name":"Carbon Loss Calculator","status":"WORKING","endpoints":["/api/carbon","/api/analysis/evidence-chain"],"note":"Automatic reference-density estimate is available when Earth Engine is authenticated."},
{"id":28,"name":"Climate–Forest Correlation","status":"WORKING","endpoints":["/api/intelligence/correlation","/api/analysis/climate-forest-correlation"]},
{"id":29,"name":"AI Evidence Chain","status":"WORKING","endpoints":["/api/analysis/evidence-chain"]},
{"id":30,"name":"Explainable AI","status":"WORKING","endpoints":["/api/intelligence/risk","/api/analysis/evidence-chain"],"model_gate":"SHAP becomes relevant after a validated trained supervised model is supplied."},
{"id":31,"name":"Natural-Language Earth Query","status":"WORKING","endpoints":["/api/query"]},
{"id":32,"name":"Automatic Investigation Report","status":"WORKING","endpoints":["/api/report","/api/report/investigation"]},
{"id":33,"name":"Regional Threat Comparison","status":"WORKING","endpoints":["/api/intelligence/compare-regions"]},
{"id":34,"name":"Forest Time Machine","status":"WORKING","endpoints":["/api/time-machine"]},
{"id":35,"name":"Live Command Center","status":"WORKING","endpoints":["/","/api/health"]},
{"id":36,"name":"Forest Digital Profile","status":"WORKING","endpoints":["/api/forest-profile"]},
{"id":37,"name":"News & Internet Intelligence","status":"WORKING","endpoints":["/api/news","/api/analysis/evidence-chain"],"note":"News is context only, never proof of causation."},
]
