from __future__ import annotations

FEATURE_CAPABILITIES = [
{"id":1,"name":"Real Satellite Monitoring","status":"WORKING","endpoints":["/api/satellite/latest","/api/map/satellite-layer","/api/gibs/layer/{layer_id}"],"sources":["Earth Search","Copernicus Data Space","NASA GIBS"]},
{"id":2,"name":"Forest Cover Monitoring","status":"WORKING_WITH_PUBLIC_FALLBACK","endpoints":["/api/layers","/api/map/gfw-layer","/api/earth-engine/layer/dynamic_world_trees"],"sources":["GFW public tiles","Sentinel-2","Dynamic World optional"]},
{"id":3,"name":"AI Deforestation Detection","status":"WORKING_BASELINE_DEEP_MODEL_OPTIONAL","endpoints":["/api/analysis/remote-change","/api/ai/change-model/status"],"sources":["Sentinel-2 L2A"]},
{"id":4,"name":"Before–After Satellite Comparison","status":"WORKING","endpoints":["/api/map/compare","/api/analysis/remote-change"]},
{"id":5,"name":"Multi-Spectral Analysis","status":"WORKING","endpoints":["/api/map/satellite-layer","/api/analysis/remote-change"],"indices":["NDVI","NDMI","NBR","NDWI"]},
{"id":6,"name":"Multi-Layer Earth Map","status":"WORKING","endpoints":["/api/layers","/api/map/gfw-layer","/api/gibs/layer/{layer_id}","/api/earth-engine/layer/{layer_id}","/api/bhuvan/tile/{z}/{x}/{y}.png"]},
{"id":7,"name":"Deep Region Investigation","status":"WORKING","endpoints":["/api/investigate","/api/analysis/evidence-chain"]},
{"id":8,"name":"Temperature Intelligence","status":"WORKING","endpoints":["/api/weather","/api/climate/anomaly"]},
{"id":9,"name":"Weather Intelligence","status":"WORKING","endpoints":["/api/weather"]},
{"id":10,"name":"Drought & Water Stress","status":"WORKING","endpoints":["/api/climate/anomaly","/api/weather","/api/earth-engine/layer/jrc_water_occurrence"]},
{"id":11,"name":"Fire & Heat Detection","status":"WORKING_WITH_PUBLIC_FALLBACK","endpoints":["/api/fire","/api/fire/intelligence","/api/eonet/events","/api/gibs/catalog"],"note":"FIRMS gives pixel-level NRT detections when the free MAP key is configured; EONET/GIBS keep the fire context operational without that key."},
{"id":12,"name":"Vegetation Health","status":"WORKING","endpoints":["/api/analysis/vegetation-series","/api/map/satellite-layer?mode=ndvi"]},
{"id":13,"name":"Environmental Anomaly Radar","status":"WORKING","endpoints":["/api/intelligence/anomaly-radar","/api/climate/anomaly"]},
{"id":14,"name":"AI Forest Doctor","status":"WORKING","endpoints":["/api/intelligence/forest-doctor","/api/analysis/evidence-chain"]},
{"id":15,"name":"Smart Warning System","status":"WORKING","endpoints":["/api/intelligence/risk","/api/analysis/evidence-chain"]},
{"id":16,"name":"Threat Prediction","status":"WORKING_BASELINE","endpoints":["/api/intelligence/predict","/api/intelligence/predict-location"],"note":"Transparent trend projection with uncertainty; not certainty."},
{"id":17,"name":"Threat Cascade Engine","status":"WORKING","endpoints":["/api/intelligence/cascade"]},
{"id":18,"name":"AI Priority Engine","status":"WORKING","endpoints":["/api/intelligence/risk","/api/intelligence/compare-regions"]},
{"id":19,"name":"Investigation/Patrol Optimizer","status":"WORKING","endpoints":["/api/patrol","/api/patrol/road-route"],"sources":["OSRM","OpenStreetMap"]},
{"id":20,"name":"AI What-If Simulator","status":"WORKING","endpoints":["/api/intelligence/what-if"]},
{"id":21,"name":"Intervention Engine","status":"WORKING","endpoints":["/api/intelligence/intervention"]},
{"id":22,"name":"Recovery Intelligence","status":"WORKING","endpoints":["/api/intelligence/recovery","/api/analysis/recovery-location"]},
{"id":23,"name":"Recovery Exit Conditions","status":"WORKING","endpoints":["/api/intelligence/recovery","/api/analysis/recovery-location"]},
{"id":24,"name":"Forest Resilience Score","status":"WORKING","endpoints":["/api/intelligence/resilience"]},
{"id":25,"name":"Protected Area Intelligence","status":"WORKING_WITH_PUBLIC_FALLBACK","endpoints":["/api/protected-area/context","/api/protected-areas","/api/protected-areas/{site_id}","/api/protected-areas/{site_id}/parcels"],"note":"Protected Planet/WDPA is preferred; OpenStreetMap protected-area containment is a credential-free fallback."},
{"id":26,"name":"Forest Fragmentation Analysis","status":"WORKING","endpoints":["/api/analysis/fragmentation","/api/analysis/remote-change"]},
{"id":27,"name":"Carbon Loss Calculator","status":"WORKING","endpoints":["/api/carbon","/api/analysis/evidence-chain"],"note":"Automatic reference-density estimate is available when a valid density source is configured."},
{"id":28,"name":"Climate–Forest Correlation","status":"WORKING","endpoints":["/api/intelligence/correlation","/api/analysis/climate-forest-correlation"]},
{"id":29,"name":"AI Evidence Chain","status":"WORKING","endpoints":["/api/analysis/evidence-chain"]},
{"id":30,"name":"Explainable AI","status":"WORKING","endpoints":["/api/intelligence/risk","/api/analysis/evidence-chain"],"model_gate":"SHAP is used only after a validated supervised model exists."},
{"id":31,"name":"Natural-Language Earth Query","status":"WORKING","endpoints":["/api/query"]},
{"id":32,"name":"Automatic Investigation Report","status":"WORKING","endpoints":["/api/report","/api/report/investigation"]},
{"id":33,"name":"Regional Threat Comparison","status":"WORKING","endpoints":["/api/intelligence/compare-regions"]},
{"id":34,"name":"Forest Time Machine","status":"WORKING","endpoints":["/api/time-machine"]},
{"id":35,"name":"Live Command Center","status":"WORKING","endpoints":["/","/api/health","/api/source-health","/api/fallbacks/status"]},
{"id":36,"name":"Forest Digital Profile","status":"WORKING","endpoints":["/api/forest-profile"]},
{"id":37,"name":"News & Internet Intelligence","status":"WORKING","endpoints":["/api/news","/api/analysis/evidence-chain"],"note":"News is context only, never proof of causation."},
]
