const API='';
const $=(id)=>document.getElementById(id);
const state={lat:null,lon:null,place:'India',investigation:null,profile:null,layers:null,active:new Map(),compareBefore:null,compareAfter:null,timeMap:null,timeScenes:[],timeIndex:0,timeTimer:null,layerGroupFilter:null};
const osmStyle={version:8,sources:{osm:{type:'raster',tiles:['https://tile.openstreetmap.org/{z}/{x}/{y}.png'],tileSize:256,attribution:'© OpenStreetMap contributors'}},layers:[{id:'osm',type:'raster',source:'osm',paint:{'raster-saturation':-.15,'raster-brightness-min':.18,'raster-brightness-max':.75,'raster-contrast':.08}}]};

function toast(msg){const t=$('toast');t.textContent=msg;t.classList.remove('hidden');setTimeout(()=>t.classList.add('hidden'),3200)}
async function api(path,opts={}){const r=await fetch(API+path,opts); if(!r.ok) throw new Error(`${r.status} ${await r.text()}`); return r.json()}
function escapeHtml(s){return String(s??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function isoDate(d){return d.toISOString().slice(0,10)}
const now=new Date(); const yearAgo=new Date(now); yearAgo.setFullYear(now.getFullYear()-1); const monthAgo=new Date(now); monthAgo.setDate(now.getDate()-30);
$('endDate').value=isoDate(now); $('startDate').value=isoDate(monthAgo); $('beforeDate').value=isoDate(yearAgo); $('afterDate').value=isoDate(now); $('timeStart').value=`${now.getFullYear()-3}-01-01`; $('timeEnd').value=isoDate(now);

const map=new maplibregl.Map({container:'map',center:[78.9,22.8],zoom:4.2,style:osmStyle});
map.addControl(new maplibregl.NavigationControl(),'top-right');
map.on('click',e=>investigate(e.lngLat.lat,e.lngLat.lng,state.place));

async function loadLayers(){const data=await api('/api/layers');state.layers=data.groups;renderLayers()}
function selectedFilters(){return {fresh:$('freshnessFilter').value,res:Number($('resolutionFilter').value||0),cloud:Number($('cloudFilter').value||50),start:$('startDate').value,end:$('endDate').value,confidence:$('confidenceFilter').value}}
function renderLayers(){const {fresh,res}=selectedFilters();$('layerGroups').innerHTML=state.layers.filter(g=>!state.layerGroupFilter||g.id===state.layerGroupFilter||(state.layerGroupFilter==='threats'&&['fire','water','human','conservation'].includes(g.id))).map(g=>{const rows=g.layers.filter(l=>(!fresh||l.freshness===fresh)&&(!res||!l.resolution_m||l.resolution_m<=res)).map(l=>`<div class="layer-row"><label><input type="checkbox" data-layer="${l.id}" ${state.active.has(l.id)?'checked':''}> ${l.label}</label><span class="layer-meta">${l.source}<br>${l.resolution_m?l.resolution_m+' m':''} ${l.freshness||''}</span></div>`).join('');return rows?`<div class="layer-group"><h3>${g.icon||''} ${g.label}</h3>${rows}</div>`:''}).join('');document.querySelectorAll('[data-layer]').forEach(x=>x.addEventListener('change',()=>toggleLayer(findLayer(x.dataset.layer),x.checked,x)))}
function findLayer(id){for(const g of state.layers||[]){const l=g.layers.find(x=>x.id===id);if(l)return l}return null}
function ensureLocation(){if(state.lat==null||state.lon==null){toast('Select a location on the map first.');return false}return true}
function removeLayer(id){const rec=state.active.get(id);if(!rec)return;try{if(map.getLayer(rec.layer))map.removeLayer(rec.layer);if(map.getSource(rec.source))map.removeSource(rec.source)}catch{}state.active.delete(id)}
function addRaster(id,tileUrl,opacity=.72){removeLayer(id);const source=`src-${id}`,layer=`lyr-${id}`;map.addSource(source,{type:'raster',tiles:[tileUrl],tileSize:256});map.addLayer({id:layer,type:'raster',source,paint:{'raster-opacity':opacity}});state.active.set(id,{source,layer})}
function addGeoPoints(id,features,color='#ff4d5a'){removeLayer(id);const source=`src-${id}`,layer=`lyr-${id}`;map.addSource(source,{type:'geojson',data:{type:'FeatureCollection',features}});map.addLayer({id:layer,type:'circle',source,paint:{'circle-radius':5,'circle-color':color,'circle-stroke-width':1,'circle-stroke-color':'#fff','circle-opacity':.82}});state.active.set(id,{source,layer})}

async function toggleLayer(def,enabled,checkbox){if(!def)return;if(!enabled){removeLayer(def.id);toast(`Disabled ${def.label}`);return}const f=selectedFilters();try{
 if(def.render==='satellite'){if(!ensureLocation())throw new Error('location required');const s=await api(`/api/map/satellite-layer?lat=${state.lat}&lon=${state.lon}&mode=${def.mode}&cloud_lt=${f.cloud}`);addRaster(def.id,s.tile_url,def.mode==='true_color'?.9:.72);toast(`${def.label}: ${s.observed_at||'scene loaded'}`)}
 else if(def.render==='gfw'){let q=`/api/map/gfw-layer?dataset=${encodeURIComponent(def.dataset)}&confidence=${f.confidence}`;if(f.start)q+=`&start_date=${f.start}`;if(f.end)q+=`&end_date=${f.end}`;const s=await api(q);addRaster(def.id,s.tile_url,.72);toast(`${def.label} enabled from GFW`)}
 else if(def.render==='earth_engine'){if(!ensureLocation())throw new Error('location required');const s=await api(`/api/earth-engine/layer/${def.ee_layer}?lat=${state.lat}&lon=${state.lon}`);addRaster(def.id,s.tile_url,.68);toast(`${def.label} enabled via Earth Engine`)}
 else if(def.render==='firms_points'){if(!ensureLocation())throw new Error('location required');const s=await api(`/api/fire?lat=${state.lat}&lon=${state.lon}&days=3`);if(!s.ok)throw new Error(s.error||'FIRMS unavailable');const feats=(s.data||[]).map(r=>({type:'Feature',geometry:{type:'Point',coordinates:[Number(r.longitude),Number(r.latitude)]},properties:r})).filter(x=>Number.isFinite(x.geometry.coordinates[0]));addGeoPoints(def.id,feats,'#ff5a3d');toast(`${feats.length} FIRMS detections rendered`)}
 else if(def.render==='overpass'){if(!ensureLocation())throw new Error('location required');const s=await api(`/api/human-pressure?lat=${state.lat}&lon=${state.lon}&radius_m=10000`);if(!s.ok)throw new Error(s.error);const feats=(s.data.elements||[]).map(e=>{const lat=e.lat??e.center?.lat,lon=e.lon??e.center?.lon;if(lat==null||lon==null)return null;return {type:'Feature',geometry:{type:'Point',coordinates:[lon,lat]},properties:e.tags||{}}}).filter(Boolean);addGeoPoints(def.id,feats,'#f4b740');toast(`${feats.length} mapped human-pressure features rendered`)}
 else {toast(`${def.label} is analysis/profile data; select a region to inspect it.`); if(checkbox)checkbox.checked=false;return}
 }catch(e){if(checkbox)checkbox.checked=false;removeLayer(def.id);toast(`${def.label}: ${String(e.message).slice(0,180)}`)}}

async function investigate(lat,lon,place='India'){state.lat=lat;state.lon=lon;state.place=place||'India';$('inspector').classList.remove('hidden');$('coords').textContent=`${lat.toFixed(5)}, ${lon.toFixed(5)}`;$('regionTitle').textContent=place||'Selected Region';$('mapStatus').textContent='Gathering real source data…';['mSatellite','mTemp','mFire','mSoil'].forEach(id=>$(id).textContent='Checking…');try{const [d,p]=await Promise.all([api(`/api/investigate?lat=${lat}&lon=${lon}&place=${encodeURIComponent(place||'India')}`),api(`/api/forest-profile?lat=${lat}&lon=${lon}&place=${encodeURIComponent(place||'India')}`)]);state.investigation=d;state.profile=p;renderInvestigation(d);renderProfile(p);$('mapStatus').textContent='Investigation loaded — every value retains source/freshness';}catch(e){toast('Investigation error: '+e.message);$('mapStatus').textContent='Some sources unavailable'}}

function renderInvestigation(d){const s=d.sources;const sat=s.earth_search?.ok?s.earth_search:s.satellite;const features=sat?.ok?(sat.data.features||[]):[];$('mSatellite').textContent=sat?.ok?(features.length?`${features.length} scenes`:'No scene'):'Unavailable';$('mSatelliteSub').textContent=sat?.ok?`${sat.provenance.resolution_m||10}m • ${sat.provenance.freshness}`:(sat?.error||'Source unavailable');const cur=s.weather.ok?s.weather.data.current:null;$('mTemp').textContent=cur&&cur.temperature_2m!=null?`${cur.temperature_2m}°C`:'Unavailable';$('mWeatherSub').textContent=cur?`${cur.relative_humidity_2m??'—'}% RH • ${s.weather.provenance.freshness}`:(s.weather.error||'Open-Meteo unavailable');const fires=s.fire.ok?(s.fire.data||[]):[];$('mFire').textContent=s.fire.ok?`${fires.length} detections`:'Not configured';$('mFireSub').textContent=s.fire.ok?s.fire.provenance.freshness:(s.fire.error||'FIRMS unavailable');$('mSoil').textContent=s.soil.ok?'Available':'Unavailable';$('mSoilSub').textContent=s.soil.ok?'250m modeled reference':(s.soil.error||'SoilGrids unavailable');const ev=[];if(sat?.ok&&features.length){const f=features[0];ev.push(`Latest suitable Sentinel-2 scene: ${f.properties?.datetime||'timestamp in STAC'}; cloud ${f.properties?.['eo:cloud_cover']??'—'}%`)}else ev.push('Sentinel-2 metadata unavailable for this request');if(cur)ev.push(`Weather: ${cur.temperature_2m??'—'}°C, humidity ${cur.relative_humidity_2m??'—'}%, cloud ${cur.cloud_cover??'—'}%`);if(s.fire.ok)ev.push(`${fires.length} FIRMS detections in configured window`);else ev.push('FIRMS MAP key not configured or service unavailable — no fire count fabricated');if(s.human_pressure.ok)ev.push(`${(s.human_pressure.data.elements||[]).length} mapped road/settlement/industrial features found nearby`);if(s.soil.ok)ev.push('SoilGrids modeled properties retrieved; reference estimate, not a field sample');$('evidenceChain').innerHTML=ev.map(x=>`<p>${escapeHtml(x)}</p>`).join('');$('evidenceRaw').textContent=JSON.stringify(d,null,2);$('environmentPanel').innerHTML=renderEnvironment(s);$('newsPanel').innerHTML=renderNews(s.news)}
function renderProfile(p){const e=p.environment||{},l=p.location||{},s=p.satellite||{},h=p.human_pressure||{},f=p.fire||{},forest=p.forest||{},t=p.terrain||{},cons=p.conservation||{};const pa=cons.inside_protected_area===true?'YES':cons.inside_protected_area===false?'NO':'—';$('profilePanel').innerHTML=`<h3>🌍 Forest Digital Profile</h3><div class="profile-grid"><div><small>Resolved area</small><b>${escapeHtml(l.display_name||state.place)}</b></div><div><small>State / District</small><b>${escapeHtml(l.state||'—')} / ${escapeHtml(l.district||'—')}</b></div><div><small>Sentinel scenes</small><b>${s.available_scenes??'—'}</b></div><div><small>Latest capture</small><b>${escapeHtml(s.latest_scene_time||'—')}</b></div><div><small>Tree probability</small><b>${forest.dynamic_world_tree_probability!=null?(forest.dynamic_world_tree_probability*100).toFixed(1)+'%':'—'}</b></div><div><small>GEDI biomass</small><b>${forest.gedi_agbd_mg_per_ha!=null?Number(forest.gedi_agbd_mg_per_ha).toFixed(1)+' Mg/ha':'—'}</b></div><div><small>Carbon density ref.</small><b>${forest.carbon_density_t_per_ha_reference!=null?Number(forest.carbon_density_t_per_ha_reference).toFixed(1)+' tC/ha':'—'}</b></div><div><small>Protected area</small><b>${pa}</b></div><div><small>Elevation</small><b>${t.elevation_m!=null?Number(t.elevation_m).toFixed(0)+' m':'—'}</b></div><div><small>Slope</small><b>${t.slope_deg!=null?Number(t.slope_deg).toFixed(1)+'°':'—'}</b></div><div><small>Temperature</small><b>${e.temperature_c??'—'} °C</b></div><div><small>Humidity</small><b>${e.humidity_pct??'—'}%</b></div><div><small>Rain</small><b>${e.rain_mm??'—'} mm</b></div><div><small>Mapped human pressure</small><b>${h.mapped_features??'—'}</b></div><div><small>Human modification ref.</small><b>${h.human_modification_reference!=null?Number(h.human_modification_reference).toFixed(2):'—'}</b></div><div><small>Population grid ref.</small><b>${h.population_reference!=null?Number(h.population_reference).toFixed(1):'—'}</b></div><div><small>Fire detections</small><b>${f.detections_in_window??'—'}</b></div><div><small>Soil</small><b>${p.soil?.ok?'SoilGrids available':'Unavailable'}</b></div></div><div id="profileTrendChart" class="profile-chart"></div><p id="profileTrendNote" class="muted-note">Loading source-backed vegetation trend…</p><p class="muted-note">${escapeHtml(p.note||'')}</p>`;loadProfileTrend()}
async function loadProfileTrend(){if(!ensureLocation()||typeof echarts==='undefined')return;const start=`${now.getFullYear()-1}-${String(now.getMonth()+1).padStart(2,'0')}-${String(now.getDate()).padStart(2,'0')}`,end=isoDate(now);try{const d=await api(`/api/analysis/vegetation-series?lat=${state.lat}&lon=${state.lon}&start=${start}&end=${end}&max_observations=8`);const pts=d.observations||d.series||[];if(!pts.length){$('profileTrendNote').textContent='No suitable cloud-screened Sentinel observations found for the trend window.';return}const chart=echarts.init($('profileTrendChart'));const dates=pts.map(x=>(x.datetime||x.date||'').slice(0,10)),ndvi=pts.map(x=>x.mean_ndvi??x.ndvi??null),forest=pts.map(x=>x.forest_fraction==null?null:Number(x.forest_fraction)*100);chart.setOption({backgroundColor:'transparent',tooltip:{trigger:'axis'},legend:{data:['Mean NDVI','Forest fraction %'],textStyle:{color:'#9db7af'}},grid:{left:42,right:20,top:34,bottom:32},xAxis:{type:'category',data:dates,axisLabel:{color:'#78958d',fontSize:9}},yAxis:[{type:'value',min:-1,max:1,axisLabel:{color:'#78958d'}},{type:'value',min:0,max:100,axisLabel:{color:'#78958d'}}],series:[{name:'Mean NDVI',type:'line',smooth:true,data:ndvi},{name:'Forest fraction %',type:'line',smooth:true,yAxisIndex:1,data:forest}]});$('profileTrendNote').textContent='Sentinel-2 source-backed vegetation trend; cloud-masked screening values, not field measurements.'}catch(e){$('profileTrendNote').textContent='Vegetation trend unavailable: '+String(e.message).slice(0,140)}}

function drawSearchBoundary(hit){const g=hit?.geojson;if(!g)return;const src='search-boundary',fill='search-boundary-fill',line='search-boundary-line';for(const id of [fill,line])if(map.getLayer(id))map.removeLayer(id);if(map.getSource(src))map.removeSource(src);map.addSource(src,{type:'geojson',data:{type:'Feature',properties:{name:hit.display_name||''},geometry:g}});map.addLayer({id:fill,type:'fill',source:src,paint:{'fill-color':'#20d67b','fill-opacity':.06}});map.addLayer({id:line,type:'line',source:src,paint:{'line-color':'#45e9a0','line-width':2,'line-opacity':.85}})}

function renderEnvironment(s){const cur=s.weather.ok?s.weather.data.current||{}:{};return `<h3>Environmental profile</h3><div class="evidence-list"><p>Temperature: ${cur.temperature_2m??'Unavailable'}°C</p><p>Humidity: ${cur.relative_humidity_2m??'Unavailable'}%</p><p>Rain: ${cur.rain??'Unavailable'} mm</p><p>Cloud cover: ${cur.cloud_cover??'Unavailable'}%</p><p>Wind: ${cur.wind_speed_10m??'Unavailable'} km/h</p><p>Soil source: ${s.soil.ok?'SoilGrids reference estimates':'Unavailable'}</p></div>`}
function renderNews(n){if(!n||!n.ok)return `<h3>News intelligence</h3><p>${escapeHtml(n?.error||'Unavailable')}</p><small>News is contextual evidence only, never proof of causation.</small>`;const arts=n.data?.articles||[];if(!arts.length)return '<h3>News intelligence</h3><p>No matching recent articles returned.</p>';return `<h3>News intelligence</h3>${arts.slice(0,8).map(a=>`<p><a target="_blank" rel="noopener" href="${a.url}">${escapeHtml(a.title||a.url)}</a><br><small>${escapeHtml(a.domain||'')} ${escapeHtml(a.seendate||'')}</small></p>`).join('')}<small>Supporting context only; correlation is not causation.</small>`}

async function doSearch(){const q=$('searchBox').value.trim();if(!q)return;try{const g=await api('/api/geocode?q='+encodeURIComponent(q));if(g.ok&&g.data?.length){const hit=g.data[0];state.place=hit.display_name||q;drawSearchBoundary(hit);map.flyTo({center:[Number(hit.lon),Number(hit.lat)],zoom:9});await investigate(Number(hit.lat),Number(hit.lon),state.place);toast('Location resolved with OpenStreetMap Nominatim');return}}catch{}try{const parsed=await api('/api/query?q='+encodeURIComponent(q));toast('Earth query parsed: '+JSON.stringify(parsed.filters));if(state.lat!=null)investigate(state.lat,state.lon,q)}catch(e){toast(e.message)}}

function openCompare(){if(!ensureLocation())return;$('compareModal').classList.remove('hidden')}
async function loadCompare(){if(!ensureLocation())return;const b=$('beforeDate').value,a=$('afterDate').value,mode=$('compareMode').value;if(!b||!a)return toast('Choose both dates');$('compareMeta').textContent='Searching real Sentinel-2 scenes…';try{const d=await api(`/api/map/compare?lat=${state.lat}&lon=${state.lon}&before_date=${b}&after_date=${a}&mode=${mode}`);setupCompareMaps(d);$('compareMeta').textContent=`Before: ${d.before.observed_at} • cloud ${d.before.cloud_cover??'—'}% | After: ${d.after.observed_at} • cloud ${d.after.cloud_cover??'—'}%`;}catch(e){$('compareMeta').textContent=e.message}}
function setupCompareMaps(d){if(state.compareBefore)state.compareBefore.remove();if(state.compareAfter)state.compareAfter.remove();const center=[state.lon,state.lat],zoom=Math.max(map.getZoom(),9);state.compareBefore=new maplibregl.Map({container:'compareBefore',center,zoom,style:osmStyle,interactive:true});state.compareAfter=new maplibregl.Map({container:'compareAfter',center,zoom,style:osmStyle,interactive:true});const add=(m,id,url)=>m.on('load',()=>{m.addSource(id,{type:'raster',tiles:[url],tileSize:256});m.addLayer({id,type:'raster',source:id,paint:{'raster-opacity':.92}})});add(state.compareBefore,'before-raster',d.before.tile_url);add(state.compareAfter,'after-raster',d.after.tile_url);let syncing=false;const sync=(src,dst)=>{if(syncing)return;syncing=true;const c=src.getCenter();dst.jumpTo({center:[c.lng,c.lat],zoom:src.getZoom(),bearing:src.getBearing(),pitch:src.getPitch()});syncing=false};state.compareBefore.on('move',()=>sync(state.compareBefore,state.compareAfter));state.compareAfter.on('move',()=>sync(state.compareAfter,state.compareBefore));setTimeout(()=>{$('compareSlider').dispatchEvent(new Event('input'));state.compareBefore.resize();state.compareAfter.resize()},250)}

async function analyzeChange(){if(!ensureLocation())return;const b=$('beforeDate').value,a=$('afterDate').value;if(!b||!a)return toast('Choose both dates');const box=$('changeResult');box.classList.remove('hidden');box.textContent='Reading real Sentinel-2 COG pixels, masking cloud/shadow/snow and calculating change…';try{const d=await api(`/api/analysis/evidence-chain?lat=${state.lat}&lon=${state.lon}&place=${encodeURIComponent(state.place)}&before_date=${b}&after_date=${a}&radius_km=2`);const c=d.change,w=d.warning;if(!c){box.textContent='No automatic change result was produced. Check scene coverage/source access.';return}box.innerHTML=`<strong>${c.candidate_area_ha??'—'} ha candidate vegetation loss</strong><br>NDVI Δ ${c.mean_ndvi_change??'—'} • screening confidence ${c.screening_confidence??'—'} • cloud masked ${(100*(c.cloud_masked_fraction||0)).toFixed(1)}%<br><b>${w.level}</b> warning ${w.score??'—'}/100 • evidence coverage ${Math.round((w.coverage||0)*100)}%<br><small>${escapeHtml(c.warning)}</small>`;renderCandidateLoss(c.geojson);const items=d.evidence_chain?.items||[];$('evidenceChain').innerHTML=`<p><b>${escapeHtml(w.level)}</b> — ${w.score??'—'}/100 evidence-normalized warning</p>`+items.map(x=>`<p><b>${escapeHtml(x.kind)}</b> · ${escapeHtml(x.source)} — ${escapeHtml(x.statement)}</p>`).join('');$('evidenceRaw').textContent=JSON.stringify(d,null,2);toast('Real before/after loss screening completed')}catch(e){box.textContent='Analysis failed: '+e.message}}
function renderCandidateLoss(geojson){const source='candidate-loss';const layer='candidate-loss-fill',line='candidate-loss-line';if(map.getLayer(line))map.removeLayer(line);if(map.getLayer(layer))map.removeLayer(layer);if(map.getSource(source))map.removeSource(source);map.addSource(source,{type:'geojson',data:geojson});map.addLayer({id:layer,type:'fill',source,paint:{'fill-color':'#ff493d','fill-opacity':.35}});map.addLayer({id:line,type:'line',source,paint:{'line-color':'#ff8b72','line-width':2}});}

async function openTime(){if(!ensureLocation())return;$('timeModal').classList.remove('hidden')}
async function loadTime(){if(!ensureLocation())return;const s=$('timeStart').value,e=$('timeEnd').value;$('timeline').textContent='Loading scene history…';try{const d=await api(`/api/time-machine?lat=${state.lat}&lon=${state.lon}&start=${s}&end=${e}&limit=100`);state.timeScenes=d.scenes;state.timeIndex=0;$('timeline').innerHTML=d.scenes.length?d.scenes.map((x,i)=>`<button class="timeline-item" data-scene="${i}"><b>${escapeHtml((x.datetime||'').slice(0,10))}</b><span>Cloud ${x.cloud_cover??'—'}%</span></button>`).join(''):'No suitable scenes found.';document.querySelectorAll('[data-scene]').forEach(btn=>btn.onclick=()=>showTimeScene(Number(btn.dataset.scene)));if(d.scenes.length)showTimeScene(0)}catch(err){$('timeline').textContent=err.message}}
function ensureTimeMap(){if(state.timeMap)return;state.timeMap=new maplibregl.Map({container:'timeMap',center:[state.lon,state.lat],zoom:Math.max(map.getZoom(),8),style:osmStyle});}
function showTimeScene(i){const scene=state.timeScenes[i];if(!scene)return;state.timeIndex=i;ensureTimeMap();document.querySelectorAll('[data-scene]').forEach(x=>x.classList.toggle('active',Number(x.dataset.scene)===i));const draw=()=>{for(const id of ['time-raster'])if(state.timeMap.getLayer(id))state.timeMap.removeLayer(id);if(state.timeMap.getSource('time-raster'))state.timeMap.removeSource('time-raster');state.timeMap.addSource('time-raster',{type:'raster',tiles:[scene.tile_url],tileSize:256});state.timeMap.addLayer({id:'time-raster',type:'raster',source:'time-raster',paint:{'raster-opacity':.92}});$('timeCaption').textContent=`${(scene.datetime||'').slice(0,10)} • cloud ${scene.cloud_cover??'—'}% • real Sentinel-2 L2A`;};if(state.timeMap.loaded())draw();else state.timeMap.once('load',draw)}
function toggleTimePlay(){if(state.timeTimer){clearInterval(state.timeTimer);state.timeTimer=null;$('playTime').textContent='▶ Play';return}if(!state.timeScenes.length)return toast('Load a timeline first');$('playTime').textContent='⏸ Pause';state.timeTimer=setInterval(()=>{state.timeIndex=(state.timeIndex+1)%state.timeScenes.length;showTimeScene(state.timeIndex)},1800)}

$('layersBtn').onclick=()=>{state.layerGroupFilter=null;document.querySelectorAll('[data-group]').forEach(x=>x.classList.remove('active'));renderLayers();$('layerDrawer').classList.remove('hidden')};document.querySelectorAll('[data-group]').forEach(btn=>btn.onclick=()=>{document.querySelectorAll('[data-group]').forEach(x=>x.classList.remove('active'));btn.classList.add('active');state.layerGroupFilter=btn.dataset.group==='fire'?'threats':btn.dataset.group;renderLayers();$('layerDrawer').classList.remove('hidden')});$('closeLayers').onclick=()=>$('layerDrawer').classList.add('hidden');$('freshnessFilter').onchange=renderLayers;$('resolutionFilter').onchange=renderLayers;$('closeInspector').onclick=()=>$('inspector').classList.add('hidden');document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));document.querySelectorAll('.tab-panel').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('tab-'+b.dataset.tab).classList.add('active')});async function loadSourceHealth(showToast=false){try{const [h,sh]=await Promise.all([api('/api/health'),api('/api/source-health')]);const by=Object.fromEntries((sh.sources||[]).map(x=>[x.source,x]));$('satHealth').textContent=(by['Earth Search']?.ok||by['Copernicus STAC']?.ok)?'Healthy':'Unavailable';$('weatherHealth').textContent=by['Open-Meteo']?.ok?'Healthy':'Unavailable';$('fireHealth').textContent=h.capabilities.firms_configured?(by['NASA FIRMS']?.ok?'Healthy':'Check source'):'Key required';$('gfwHealth').textContent='Public tiles';if(showToast)toast(`${sh.healthy_sources}/${sh.configured_sources} configured providers healthy`);return sh}catch(e){if(showToast)toast('Source health unavailable');return null}}
$('healthBtn').onclick=()=>loadSourceHealth(true);$('riskDemoBtn').onclick=async()=>{if(!ensureLocation())return;try{const before=$('beforeDate').value,after=$('afterDate').value;toast('Building source-backed evidence chain…');const q=`/api/analysis/evidence-chain?lat=${state.lat}&lon=${state.lon}&place=${encodeURIComponent(state.place||'India')}&before_date=${encodeURIComponent(before)}&after_date=${encodeURIComponent(after)}`;const r=await api(q);const w=r.warning||{};const evidence=(r.evidence_chain?.items||r.evidence||[]);const coverage=w.coverage==null?'—':Math.round(w.coverage*100);$('evidenceChain').innerHTML=`<p><b>${escapeHtml(w.level||'UNASSESSED')}</b> — ${w.score??'—'}/100 • evidence coverage ${coverage}%</p>`+(w.factors||[]).slice(0,7).map(f=>`<p>${escapeHtml(f.factor||f.name||'factor')}: +${f.contribution??f.value??'—'} • ${escapeHtml(f.evidence||'')}</p>`).join('')+evidence.slice(0,5).map(e=>`<p>${escapeHtml(e.kind||e.type||e.classification||'EVIDENCE')}: ${escapeHtml(e.statement||e.summary||e.description||e.source||'source-backed item')}</p>`).join('');if(r.change?.geojson)renderChangeMask(r.change.geojson);toast('Source-backed explainable warning completed')}catch(e){toast('Risk analysis failed: '+e.message)}};$('reportBtn').onclick=async()=>{if(!ensureLocation())return;try{const before=$('beforeDate').value,after=$('afterDate').value;const url=`/api/report/investigation?lat=${state.lat}&lon=${state.lon}&place=${encodeURIComponent(state.place||'India')}&before_date=${encodeURIComponent(before)}&after_date=${encodeURIComponent(after)}`;toast('Generating source-backed investigation report…');const r=await fetch(url);if(!r.ok)throw new Error(`${r.status} ${await r.text()}`);const blob=await r.blob();const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='vanrakshak-investigation-report.pdf';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000);toast('Investigation report generated')}catch(e){toast('Report failed: '+e.message)}};$('searchBtn').onclick=doSearch;$('searchBox').addEventListener('keydown',e=>{if(e.key==='Enter')doSearch()});$('compareBtn').onclick=openCompare;$('compareNav').onclick=openCompare;$('closeCompare').onclick=()=>$('compareModal').classList.add('hidden');$('loadCompare').onclick=loadCompare;$('compareSlider').oninput=e=>{$('compareAfterWrap').style.width=`${e.target.value}%`;if(state.compareAfter)state.compareAfter.resize()};$('timeNav').onclick=openTime;$('closeTime').onclick=()=>{if(state.timeTimer){clearInterval(state.timeTimer);state.timeTimer=null}$('timeModal').classList.add('hidden')};$('loadTime').onclick=loadTime;$('playTime').onclick=toggleTimePlay;$('forestProfileNav').onclick=()=>{if(!ensureLocation())return;$('inspector').classList.remove('hidden');document.querySelector('[data-tab="profile"]').click()};$('alertsNav').onclick=async()=>{if(!state.layers)return;const def=findLayer('forest_loss');const fake={checked:true};await toggleLayer(def,true,fake)};

$('analyzeChange').onclick=analyzeChange;
$('predictionNav').onclick=()=>{$('intelligenceModal').classList.remove('hidden')};
$('closeIntelligence').onclick=()=>$('intelligenceModal').classList.add('hidden');
$('runPrediction').onclick=async()=>{try{const values=$('predictionValues').value.split(',').map(Number).filter(Number.isFinite);const r=await api('/api/intelligence/predict',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({values,steps:3,floor:0,ceiling:100})});$('predictionResult').textContent=JSON.stringify(r,null,2)}catch(e){$('predictionResult').textContent=e.message}};
$('runLocationPrediction').onclick=async()=>{if(!ensureLocation())return;try{$('predictionResult').textContent='Reading historical Sentinel-2 observations…';const r=await api(`/api/intelligence/predict-location?lat=${state.lat}&lon=${state.lon}&start=${isoDate(yearAgo)}&end=${isoDate(now)}&max_observations=8`);$('predictionResult').textContent=JSON.stringify(r,null,2)}catch(e){$('predictionResult').textContent=e.message}};
$('runWhatIf').onclick=async()=>{try{const sources=state.investigation?.sources||{},fires=sources.fire?.ok?(sources.fire.data||[]).length:0,pressure=sources.human_pressure?.ok?Math.min((sources.human_pressure.data?.count||0)/80,1):0;const payload={base:{ndvi_drop:0,temp_anomaly_c:0,rainfall_deficit_pct:0,fire_signal:Math.min(fires/10,1),protected_area:false,fragmentation_change:0,human_pressure:pressure,model_confidence:.5},temperature_delta_c:Number($('whatTemp').value||0),rainfall_delta_pct:Number($('whatRain').value||0),fire_delta:Number($('whatFire').value||0),ndvi_delta:0};const r=await api('/api/intelligence/what-if',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});$('whatIfResult').textContent=JSON.stringify(r,null,2)}catch(e){$('whatIfResult').textContent=e.message}};
$('patrolNav').onclick=()=>{if(!ensureLocation())return;$('patrolModal').classList.remove('hidden')};
$('closePatrol').onclick=()=>$('patrolModal').classList.add('hidden');
$('runPatrol').onclick=async()=>{try{const rows=$('patrolPoints').value.trim().split(/\n+/).filter(Boolean).map((r,i)=>{const [lat,lon,priority]=r.split(',').map(Number);if(!Number.isFinite(lat)||!Number.isFinite(lon)||!Number.isFinite(priority))throw new Error(`Bad row ${i+1}`);return {id:`alert-${i+1}`,lat,lon,priority}});if(!rows.length)throw new Error('Add at least one patrol point');const body={start_lat:state.lat,start_lon:state.lon,points:rows};const r=await api('/api/patrol/road-route',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});$('patrolResult').textContent=JSON.stringify(r,null,2);if(r.road_route?.geometry)renderPatrolRoute(r.road_route.geometry);toast('Patrol route calculated')}catch(e){$('patrolResult').textContent=e.message}};
function renderPatrolRoute(geometry){for(const id of ['patrol-route'])if(map.getLayer(id))map.removeLayer(id);if(map.getSource('patrol-route'))map.removeSource('patrol-route');map.addSource('patrol-route',{type:'geojson',data:{type:'Feature',properties:{},geometry}});map.addLayer({id:'patrol-route',type:'line',source:'patrol-route',paint:{'line-color':'#42dca3','line-width':4,'line-opacity':.9}})}
$('reportsNav').onclick=()=>$('reportBtn').click();
$('addBhuvan').onclick=()=>{const layer=$('bhuvanLayer').value.trim();if(!layer)return toast('Enter an exact Bhuvan WMS layer name');const id='bhuvan-custom';try{removeLayer(id)}catch{}const tile=`/api/bhuvan/tile/{z}/{x}/{y}.png?layer=${encodeURIComponent(layer)}`;addRaster(id,tile,.78);toast('Bhuvan WMS layer added')};


loadLayers().catch(e=>toast('Layer registry failed: '+e.message));loadSourceHealth(false);$('healthBtn').click();
